spring:
  profiles:
    include: common
  webflux:
    base-path: /app
  main:
    allow-bean-definition-overriding: true
server:
  port: 19091
  servlet:
    context-path: /app
system:
  config:
    debug: true